### ISSUE TITLE
Permission required for downloading data

### ISSUE THREAD

**Issue by ShihaoShao-GH** [pointW/equidiff#1]
Dear authors,

Congratulations on your work being selected as a Best Paper Award Finalist! I have been attempting to reproduce your results; however, I encountered "permission denied" errors when trying to access the data, both through  `gdown` command in your code and directly via browser. Could you please assist me with this issue? Apologize if I have overlooked anything.

Cheers,
Shihao Shao

**Comment by pointW** [comment]
Hi Shihao, could you try to follow the dataset download in Mimicgen: https://mimicgen.github.io/docs/datasets/mimicgen_corl_2023.html?

**Comment by ShihaoShao-GH** [comment]
> Hi Shihao, could you try to follow the dataset download in Mimicgen: https://mimicgen.github.io/docs/datasets/mimicgen_corl_2023.html?

Thanks for your prompt response! Will check and see if it works.

**Comment by ShihaoShao-GH** [comment]
Downloading from HuggingFace has resolved the issue. Thank you!
